#!/usr/bin/env python3
from __future__ import annotations

import json
import os
from datetime import datetime, timezone
from pathlib import Path


def norm(value: str) -> str:
    return value.strip() if value and value.strip() else "UNKNOWN"


def main() -> int:
    path = Path(os.environ["BASELINE_META_FILE"])
    payload = {
        "captured_at_utc": datetime.now(timezone.utc).isoformat(),
        "run": {
            "timestamp": os.environ["TIMESTAMP"],
            "scenario_id": os.environ["SCENARIO"],
            "runs": int(os.environ["RUNS"]),
        },
        "baseline_reference": os.environ["BASELINE_FILE"],
        "git": {
            "branch": norm(os.environ.get("BRANCH_NAME", "")),
            "short_sha": norm(os.environ.get("SHORT_SHA", "")),
            "full_sha": norm(os.environ.get("FULL_SHA", "")),
        },
        "note": "Generated by scripts/run_npc_bench.sh. This benchmark run does not modify tracked markdown docs.",
    }

    with path.open("w", encoding="utf-8") as f:
        json.dump(payload, f, ensure_ascii=False, indent=2)
        f.write("\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
